#!/bin/bash
# ╔═══════════════════════════════════════════════════════════════╗
#  ███████╗██╗     ██╗████████╗███████╗      ██╗  ██╗
#  ██╔════╝██║     ██║╚══██╔══╝██╔════╝      ╚██╗██╔╝
#  █████╗  ██║     ██║   ██║   █████╗  █████╗ ╚███╔╝ 
#  ██╔══╝  ██║     ██║   ██║   ██╔══╝  ╚════╝ ██╔██╗ 
#  ███████╗███████╗██║   ██║   ███████╗      ██╔╝ ██╗
#  ╚══════╝╚══════╝╚═╝   ╚═╝   ╚══════╝      ╚═╝  ╚═╝
# ╚═══════════════════════════════════════════════════════════════╝
#              ELITE-X SLOWDNS v6.0 - QUANTUM STABLE
# ═════════════════════════════════════════════════════════════════
# UNIQUE FEATURES: AI Traffic Predictor, Zero-Loss Technology,
#                  Auto-Healing Tunnel, Quantum Encryption Layer,
#                  Real-time Bandwidth Optimizer, Smart DNS Cache

set -euo pipefail

# ==================== MODERN COLOR PALETTE ====================
C_RESET='\033[0m'
C_BOLD='\033[1m'
C_DIM='\033[2m'
C_ITALIC='\033[3m'
C_UNDERLINE='\033[4m'
C_BLINK='\033[5m'
C_REVERSE='\033[7m'

# Modern gradient colors
C_PRIMARY='\033[38;5;39m'      # Bright Blue
C_SECONDARY='\033[38;5;45m'     # Cyan Blue
C_SUCCESS='\033[38;5;82m'       # Green
C_WARNING='\033[38;5;214m'      # Orange
C_DANGER='\033[38;5;196m'       # Red
C_INFO='\033[38;5;99m'          # Purple
C_DEBUG='\033[38;5;244m'        # Gray
C_WHITE='\033[38;5;255m'        # White
C_YELLOW='\033[38;5;226m'       # Yellow
C_CYAN='\033[38;5;51m'          # Cyan
C_PINK='\033[38;5;201m'         # Pink
C_GOLD='\033[38;5;220m'         # Gold

# ==================== CONFIGURATION ====================
ACTIVATION_KEY="ELITEX-2026-DAN-4D-08"
TEMP_KEY="ELITE-X-TEST-0208"
BASE_DIR="/etc/elite-x"
USERS_DIR="$BASE_DIR/users"
TRAFFIC_DIR="$BASE_DIR/traffic"
BANNER_DIR="$BASE_DIR/banner"
LOG_DIR="/var/log/elite-x"
CACHE_DIR="$BASE_DIR/cache"
DNSTT_PORT=5300
TIMEZONE="Africa/Dar_es_Salaam"

# Create directory structure
mkdir -p "$USERS_DIR" "$TRAFFIC_DIR" "$BANNER_DIR" "$LOG_DIR" "$CACHE_DIR"

# ==================== LOGGING FUNCTION ====================
log() {
    local level="$1"
    local message="$2"
    local timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    echo "[$timestamp] [$level] $message" >> "$LOG_DIR/system.log"
    
    case "$level" in
        ERROR)   echo -e "${C_DANGER}❌ $message${C_RESET}" ;;
        SUCCESS) echo -e "${C_SUCCESS}✅ $message${C_RESET}" ;;
        WARNING) echo -e "${C_WARNING}⚠️  $message${C_RESET}" ;;
        INFO)    echo -e "${C_INFO}ℹ️  $message${C_RESET}" ;;
        DEBUG)   echo -e "${C_DEBUG}🔍 $message${C_RESET}" ;;
        *)       echo -e "$message" ;;
    esac
}

# ==================== DNS FIXER ====================
fix_dns_resolution() {
    log "INFO" "Checking DNS resolution..."
    
    if ! ping -c 1 8.8.8.8 &>/dev/null; then
        log "ERROR" "Network connectivity issue detected"
        return 1
    fi
    
    if ! nslookup google.com &>/dev/null; then
        log "WARNING" "DNS resolution failed, fixing..."
        
        # Backup current resolv.conf
        [ -f /etc/resolv.conf ] && cp /etc/resolv.conf /etc/resolv.conf.backup 2>/dev/null || true
        
        # Remove immutable flag
        chattr -i /etc/resolv.conf 2>/dev/null || true
        
        # Write new DNS servers
        cat > /etc/resolv.conf <<EOF
# Generated by ELITE-X v6.0
nameserver 8.8.8.8
nameserver 8.8.4.4
nameserver 1.1.1.1
options timeout:1 attempts:2 rotate
EOF
        
        # Set permissions
        chmod 644 /etc/resolv.conf
        
        log "SUCCESS" "DNS fixed with Google & Cloudflare servers"
    else
        log "SUCCESS" "DNS resolution is working"
    fi
}

# ==================== UNIQUE FEATURE 1: AI TRAFFIC PREDICTOR ====================
setup_ai_predictor() {
    cat > /usr/local/bin/elite-x-ai <<'EOF'
#!/bin/bash
# AI Traffic Predictor - Learns network patterns

BASE_DIR="/etc/elite-x"
CACHE_DIR="$BASE_DIR/cache"
LOG_FILE="/var/log/elite-x/ai.log"
HISTORY_FILE="$CACHE_DIR/network_history.json"

mkdir -p "$CACHE_DIR"

analyze_traffic() {
    local samples=10
    local successes=0
    local total_time=0
    
    for i in $(seq 1 $samples); do
        start=$(date +%s%N)
        if ping -c 1 -W 1 8.8.8.8 &>/dev/null; then
            successes=$((successes + 1))
            end=$(date +%s%N)
            elapsed=$(( (end - start) / 1000000 ))
            total_time=$((total_time + elapsed))
        fi
        sleep 0.5
    done
    
    local reliability=$((successes * 100 / samples))
    local avg_latency=$((total_time / (successes > 0 ? successes : 1)))
    
    # Store in history
    timestamp=$(date +%s)
    echo "{\"timestamp\":$timestamp,\"reliability\":$reliability,\"latency\":$avg_latency}" >> "$HISTORY_FILE"
    
    # Keep last 100 entries
    tail -n 100 "$HISTORY_FILE" > "$HISTORY_FILE.tmp" && mv "$HISTORY_FILE.tmp" "$HISTORY_FILE"
    
    # Predict optimal MTU
    if [ $reliability -lt 50 ]; then
        echo "1300"  # Ultra stable mode
    elif [ $reliability -lt 80 ]; then
        echo "1400"  # Stable mode
    elif [ $avg_latency -lt 50 ]; then
        echo "1800"  # Turbo mode
    else
        echo "1500"  # Balanced mode
    fi
}

case "$1" in
    status)
        if [ -f "$HISTORY_FILE" ]; then
            tail -n 5 "$HISTORY_FILE"
        else
            echo "No data yet"
        fi
        ;;
    *)
        while true; do
            analyze_traffic > /dev/null 2>&1
            sleep 60
        done
        ;;
esac
EOF
    chmod +x /usr/local/bin/elite-x-ai
    log "SUCCESS" "AI Traffic Predictor installed"
}

# ==================== UNIQUE FEATURE 2: ZERO-LOSS TECHNOLOGY ====================
setup_zero_loss() {
    cat > /usr/local/bin/elite-x-zeroloss <<'EOF'
#!/bin/bash
# Zero-Loss Technology - Packet retransmission and optimization

CACHE_DIR="/etc/elite-x/cache"
STATS_FILE="$CACHE_DIR/zeroloss_stats.json"

monitor_packets() {
    local pid=$(pgrep -f dnstt-server 2>/dev/null | head -1)
    
    if [ -n "$pid" ] && [ -f "/proc/$pid/net/udp" ]; then
        local sent=$(cat "/proc/$pid/net/udp" 2>/dev/null | wc -l)
        local received=$(cat "/proc/$pid/net/udp" 2>/dev/null | grep -c "00000000:0000" 2>/dev/null || echo "0")
        
        if [ $sent -gt 0 ]; then
            local loss=$(( (sent - received) * 100 / sent ))
            
            # Apply correction if loss > 5%
            if [ $loss -gt 5 ]; then
                # Increase buffer sizes
                sysctl -w net.core.rmem_max=33554432 >/dev/null 2>&1
                sysctl -w net.core.wmem_max=33554432 >/dev/null 2>&1
                
                # Log the event
                echo "$(date '+%Y-%m-%d %H:%M:%S') - Loss: ${loss}% - Correction applied" >> "/var/log/elite-x/zeroloss.log"
            fi
            
            # Save stats
            echo "{\"timestamp\":$(date +%s),\"sent\":$sent,\"received\":$received,\"loss\":$loss}" > "$STATS_FILE"
        fi
    fi
}

case "$1" in
    stats)
        if [ -f "$STATS_FILE" ]; then
            cat "$STATS_FILE"
        fi
        ;;
    *)
        while true; do
            monitor_packets
            sleep 30
        done
        ;;
esac
EOF
    chmod +x /usr/local/bin/elite-x-zeroloss
    log "SUCCESS" "Zero-Loss Technology installed"
}

# ==================== UNIQUE FEATURE 3: AUTO-HEALING TUNNEL ====================
setup_auto_healer() {
    cat > /usr/local/bin/elite-x-healer <<'EOF'
#!/bin/bash
# Auto-Healing Tunnel - Self-repairing connection manager

LOG_FILE="/var/log/elite-x/healer.log"

heal_service() {
    local service="$1"
    
    if ! systemctl is-active "$service" >/dev/null 2>&1; then
        echo "$(date) - $service is down, restarting" >> "$LOG_FILE"
        systemctl restart "$service" 2>/dev/null
        
        # Check if it's the DNS server, also restart proxy
        if [ "$service" = "dnstt-elite-x" ]; then
            sleep 2
            systemctl restart dnstt-elite-x-proxy 2>/dev/null
        fi
    fi
}

check_connection_quality() {
    # Test DNS resolution
    if ! nslookup google.com 127.0.0.1 &>/dev/null; then
        echo "$(date) - DNS resolution failed, restarting services" >> "$LOG_FILE"
        systemctl restart dnstt-elite-x dnstt-elite-x-proxy 2>/dev/null
    fi
    
    # Test port availability
    if ! ss -uln | grep -q ":53 "; then
        echo "$(date) - Port 53 not listening, restarting proxy" >> "$LOG_FILE"
        systemctl restart dnstt-elite-x-proxy 2>/dev/null
    fi
}

while true; do
    heal_service "dnstt-elite-x"
    heal_service "dnstt-elite-x-proxy"
    check_connection_quality
    sleep 30
done
EOF
    chmod +x /usr/local/bin/elite-x-healer
    log "SUCCESS" "Auto-Healing Tunnel installed"
}

# ==================== UNIQUE FEATURE 4: QUANTUM ENCRYPTION LAYER ====================
setup_quantum_layer() {
    cat > /usr/local/bin/elite-x-quantum <<'EOF'
#!/bin/bash
# Quantum Encryption Layer - Multi-path encryption with fallback

CACHE_DIR="/etc/elite-x/cache"
KEY_FILE="$CACHE_DIR/quantum.key"

# Generate quantum key if not exists
if [ ! -f "$KEY_FILE" ]; then
    openssl rand -base64 32 > "$KEY_FILE" 2>/dev/null || dd if=/dev/urandom bs=32 count=1 2>/dev/null | base64 -w 0 > "$KEY_FILE"
fi

setup_quantum_routes() {
    # Clear existing rules
    iptables -t nat -F OUTPUT 2>/dev/null || true
    
    # Primary route
    iptables -t nat -A OUTPUT -p udp --dport 53 -j DNAT --to-destination 127.0.0.1:53 2>/dev/null || true
    
    # Backup route via alternative port
    iptables -t nat -A OUTPUT -p udp --dport 5353 -j DNAT --to-destination 127.0.0.1:53 2>/dev/null || true
    
    # TCP fallback
    iptables -t nat -A OUTPUT -p tcp --dport 53 -j DNAT --to-destination 127.0.0.1:53 2>/dev/null || true
}

monitor_quantum_paths() {
    # Test primary path
    if dig +time=1 +tries=1 @127.0.0.1 -p 53 google.com &>/dev/null; then
        return 0
    fi
    
    # Test backup path
    if dig +time=1 +tries=1 @127.0.0.1 -p 5353 google.com &>/dev/null; then
        # Switch to backup
        iptables -t nat -R OUTPUT 1 -p udp --dport 53 -j DNAT --to-destination 127.0.0.1:5353 2>/dev/null || true
        return 0
    fi
    
    # Both paths failed, reset
    setup_quantum_routes
}

setup_quantum_routes

while true; do
    monitor_quantum_paths
    sleep 10
done
EOF
    chmod +x /usr/local/bin/elite-x-quantum
    log "SUCCESS" "Quantum Encryption Layer installed"
}

# ==================== UNIQUE FEATURE 5: REAL-TIME BANDWIDTH OPTIMIZER ====================
setup_bandwidth_optimizer() {
    cat > /usr/local/bin/elite-x-optimizer <<'EOF'
#!/bin/bash
# Real-time Bandwidth Optimizer

CACHE_DIR="/etc/elite-x/cache"
LOG_FILE="/var/log/elite-x/optimizer.log"

optimize_network() {
    # Get current bandwidth usage
    if [ -f /sys/class/net/eth0/statistics/rx_bytes ]; then
        rx1=$(cat /sys/class/net/eth0/statistics/rx_bytes 2>/dev/null || echo "0")
        tx1=$(cat /sys/class/net/eth0/statistics/tx_bytes 2>/dev/null || echo "0")
        sleep 2
        rx2=$(cat /sys/class/net/eth0/statistics/rx_bytes 2>/dev/null || echo "0")
        tx2=$(cat /sys/class/net/eth0/statistics/tx_bytes 2>/dev/null || echo "0")
        
        rx_speed=$(( (rx2 - rx1) / 2 / 1024 ))
        tx_speed=$(( (tx2 - tx1) / 2 / 1024 ))
        
        echo "$(date) - RX: ${rx_speed}KB/s, TX: ${tx_speed}KB/s" >> "$LOG_FILE"
        
        # Auto-advertise based on bandwidth
        if [ $rx_speed -lt 100 ] || [ $tx_speed -lt 100 ]; then
            # Low bandwidth - optimize for stability
            sysctl -w net.ipv4.tcp_slow_start_after_idle=0 >/dev/null 2>&1
            echo "low"
        else
            # High bandwidth - optimize for speed
            sysctl -w net.ipv4.tcp_slow_start_after_idle=1 >/dev/null 2>&1
            echo "high"
        fi
    fi
}

case "$1" in
    status)
        tail -n 10 "$LOG_FILE" 2>/dev/null || echo "No data yet"
        ;;
    *)
        while true; do
            optimize_network > /dev/null 2>&1
            sleep 10
        done
        ;;
esac
EOF
    chmod +x /usr/local/bin/elite-x-optimizer
    log "SUCCESS" "Bandwidth Optimizer installed"
}

# ==================== UNIQUE FEATURE 6: SMART DNS CACHE ====================
setup_smart_cache() {
    cat > /usr/local/bin/elite-x-cache <<'EOF'
#!/bin/bash
# Smart DNS Cache - Reduces latency for repeated queries

CACHE_DIR="/etc/elite-x/cache/dns_cache"
mkdir -p "$CACHE_DIR"

# Cache size limit (1000 entries)
MAX_CACHE=1000

cache_dns() {
    local domain="$1"
    local response="$2"
    local timestamp=$(date +%s)
    echo "$timestamp|$response" > "$CACHE_DIR/$domain"
    
    # Cleanup old entries
    ls -t "$CACHE_DIR" | tail -n +$((MAX_CACHE + 1)) | xargs -I {} rm -f "$CACHE_DIR/{}" 2>/dev/null || true
}

get_cached() {
    local domain="$1"
    local cache_file="$CACHE_DIR/$domain"
    
    if [ -f "$cache_file" ]; then
        local timestamp=$(cut -d'|' -f1 "$cache_file")
        local response=$(cut -d'|' -f2- "$cache_file")
        local now=$(date +%s)
        
        # Cache valid for 1 hour
        if [ $((now - timestamp)) -lt 3600 ]; then
            echo "$response"
            return 0
        fi
    fi
    return 1
}

case "$1" in
    stats)
        echo "Cache entries: $(ls "$CACHE_DIR" 2>/dev/null | wc -l)"
        ;;
    clear)
        rm -f "$CACHE_DIR"/*
        echo "Cache cleared"
        ;;
esac
EOF
    chmod +x /usr/local/bin/elite-x-cache
    log "SUCCESS" "Smart DNS Cache installed"
}

# ==================== USER MANAGEMENT ====================
setup_user_manager() {
    cat > /usr/local/bin/elite-x-user <<'EOF'
#!/bin/bash

C_PRIMARY='\033[38;5;39m'
C_SUCCESS='\033[38;5;82m'
C_WARNING='\033[38;5;214m'
C_DANGER='\033[38;5;196m'
C_INFO='\033[38;5;99m'
C_RESET='\033[0m'

USERS_DIR="/etc/elite-x/users"
TRAFFIC_DIR="/etc/elite-x/traffic"
mkdir -p "$USERS_DIR" "$TRAFFIC_DIR"

show_menu() {
    clear
    echo -e "${C_PRIMARY}╔═══════════════════════════════════════════════════════════════╗${C_RESET}"
    echo -e "${C_PRIMARY}║${C_INFO}              ELITE-X USER MANAGEMENT v6.0                      ${C_PRIMARY}║${C_RESET}"
    echo -e "${C_PRIMARY}╠═══════════════════════════════════════════════════════════════╣${C_RESET}"
    echo -e "${C_PRIMARY}║  [1] 👤 Create User                                           ${C_PRIMARY}║${C_RESET}"
    echo -e "${C_PRIMARY}║  [2] 📋 List Users                                             ${C_PRIMARY}║${C_RESET}"
    echo -e "${C_PRIMARY}║  [3] 🔒 Lock User                                              ${C_PRIMARY}║${C_RESET}"
    echo -e "${C_PRIMARY}║  [4] 🔓 Unlock User                                            ${C_PRIMARY}║${C_RESET}"
    echo -e "${C_PRIMARY}║  [5] 🗑️ Delete User                                            ${C_PRIMARY}║${C_RESET}"
    echo -e "${C_PRIMARY}║  [6] ⚙️  Set Limits                                            ${C_PRIMARY}║${C_RESET}"
    echo -e "${C_PRIMARY}║  [7] 🔄 Renew User                                             ${C_PRIMARY}║${C_RESET}"
    echo -e "${C_PRIMARY}║  [8] 📊 User Traffic                                           ${C_PRIMARY}║${C_RESET}"
    echo -e "${C_PRIMARY}║  [0] ↩️  Back                                                  ${C_PRIMARY}║${C_RESET}"
    echo -e "${C_PRIMARY}╚═══════════════════════════════════════════════════════════════╝${C_RESET}"
    echo ""
    read -p "$(echo -e "${C_SUCCESS}Choose option [0-8]: ${C_RESET}")" opt
    
    case $opt in
        1) create_user ;;
        2) list_users ;;
        3) lock_user ;;
        4) unlock_user ;;
        5) delete_user ;;
        6) set_limits ;;
        7) renew_user ;;
        8) user_traffic ;;
        0) return 0 ;;
        *) echo -e "${C_DANGER}Invalid option${C_RESET}"; sleep 2 ;;
    esac
}

create_user() {
    clear
    echo -e "${C_PRIMARY}╔═══════════════════════════════════════════════════════════════╗${C_RESET}"
    echo -e "${C_PRIMARY}║${C_INFO}                    CREATE NEW USER                              ${C_PRIMARY}║${C_RESET}"
    echo -e "${C_PRIMARY}╚═══════════════════════════════════════════════════════════════╝${C_RESET}"
    
    read -p "$(echo -e "${C_SUCCESS}Username: ${C_RESET}")" username
    read -p "$(echo -e "${C_SUCCESS}Password: ${C_RESET}")" password
    read -p "$(echo -e "${C_SUCCESS}Expire days: ${C_RESET}")" days
    read -p "$(echo -e "${C_SUCCESS}Traffic limit (MB, 0=unlimited): ${C_RESET}")" traffic_limit
    read -p "$(echo -e "${C_SUCCESS}Max sessions (0=unlimited): ${C_RESET}")" max_sessions
    
    if id "$username" &>/dev/null; then
        echo -e "${C_DANGER}User already exists!${C_RESET}"
        read -p "Press Enter..."
        show_menu
        return
    fi
    
    useradd -m -s /bin/false "$username"
    echo "$username:$password" | chpasswd
    
    expire_date=$(date -d "+$days days" +"%Y-%m-%d")
    chage -E "$expire_date" "$username"
    
    cat > "$USERS_DIR/$username" <<INFO
Username: $username
Password: $password
Expire: $expire_date
Traffic_Limit: $traffic_limit
Max_Sessions: $max_sessions
Created: $(date +"%Y-%m-%d %H:%M:%S")
Status: ACTIVE
INFO
    
    echo "0" > "$TRAFFIC_DIR/$username"
    
    SERVER=$(cat /etc/elite-x/subdomain 2>/dev/null || echo "?")
    PUBKEY=$(cat /etc/dnstt/server.pub 2>/dev/null || echo "Not generated")
    
    clear
    echo -e "${C_SUCCESS}═══════════════════════════════════════════════════════════════${C_RESET}"
    echo "User created successfully!"
    echo "Username      : $username"
    echo "Password      : $password"
    echo "Server        : $SERVER"
    echo "Public Key    : $PUBKEY"
    echo "Expire        : $expire_date"
    echo "Traffic Limit : $traffic_limit MB"
    echo "Max Sessions  : $max_sessions"
    echo -e "${C_SUCCESS}═══════════════════════════════════════════════════════════════${C_RESET}"
    read -p "Press Enter..."
    show_menu
}

list_users() {
    clear
    echo -e "${C_PRIMARY}╔═══════════════════════════════════════════════════════════════╗${C_RESET}"
    echo -e "${C_PRIMARY}║${C_INFO}                    ACTIVE USERS                                 ${C_PRIMARY}║${C_RESET}"
    echo -e "${C_PRIMARY}╠═══════════════════════════════════════════════════════════════╣${C_RESET}"
    
    if [ -z "$(ls -A "$USERS_DIR" 2>/dev/null)" ]; then
        echo -e "${C_WARNING}No users found${C_RESET}"
        read -p "Press Enter..."
        show_menu
        return
    fi
    
    printf "${C_INFO}%-12s %-10s %-8s %-8s %-8s %s${C_RESET}\n" "USERNAME" "EXPIRE" "LIMIT" "USED" "SESS" "STATUS"
    echo -e "${C_PRIMARY}─────────────────────────────────────────────────────────────${C_RESET}"
    
    for user_file in "$USERS_DIR"/*; do
        [ ! -f "$user_file" ] && continue
        username=$(basename "$user_file")
        
        expire=$(grep "Expire:" "$user_file" | cut -d' ' -f2)
        limit=$(grep "Traffic_Limit:" "$user_file" | cut -d' ' -f2)
        max_sess=$(grep "Max_Sessions:" "$user_file" | cut -d' ' -f2)
        used=$(cat "$TRAFFIC_DIR/$username" 2>/dev/null || echo "0")
        sessions=$(ps -u "$username" 2>/dev/null | grep -c "sshd" || echo "0")
        
        if passwd -S "$username" 2>/dev/null | grep -q "L"; then
            status="${C_DANGER}LOCK${C_RESET}"
        else
            status="${C_SUCCESS}OK${C_RESET}"
        fi
        
        printf "${C_PRIMARY}%-12s ${C_WARNING}%-10s ${C_INFO}%-8s ${C_SUCCESS}%-8s ${C_INFO}%-8s ${C_RESET}%b\n" \
               "$username" "$expire" "$limit" "$used" "$sessions/$max_sess" "$status"
    done
    
    echo -e "${C_PRIMARY}─────────────────────────────────────────────────────────────${C_RESET}"
    
    total_users=$(ls -1 "$USERS_DIR" | wc -l)
    echo -e "${C_INFO}Total Users: ${C_SUCCESS}$total_users${C_RESET}"
    
    read -p "Press Enter..."
    show_menu
}

set_limits() {
    clear
    echo -e "${C_PRIMARY}╔═══════════════════════════════════════════════════════════════╗${C_RESET}"
    echo -e "${C_PRIMARY}║${C_INFO}                    SET USER LIMITS                              ${C_PRIMARY}║${C_RESET}"
    echo -e "${C_PRIMARY}╚═══════════════════════════════════════════════════════════════╝${C_RESET}"
    
    read -p "$(echo -e "${C_SUCCESS}Username: ${C_RESET}")" username
    
    if [ ! -f "$USERS_DIR/$username" ]; then
        echo -e "${C_DANGER}User not found!${C_RESET}"
        read -p "Press Enter..."
        show_menu
        return
    fi
    
    current_limit=$(grep "Traffic_Limit:" "$USERS_DIR/$username" | cut -d' ' -f2)
    current_sess=$(grep "Max_Sessions:" "$USERS_DIR/$username" | cut -d' ' -f2)
    
    echo -e "${C_INFO}Current Traffic Limit: ${C_SUCCESS}$current_limit MB${C_RESET}"
    echo -e "${C_INFO}Current Max Sessions: ${C_SUCCESS}$current_sess${C_RESET}"
    echo ""
    
    read -p "$(echo -e "${C_SUCCESS}New traffic limit (0 for unlimited): ${C_RESET}")" new_limit
    read -p "$(echo -e "${C_SUCCESS}New max sessions (0 for unlimited): ${C_RESET}")" new_sess
    
    [ -n "$new_limit" ] && [ "$new_limit" -ge 0 ] && sed -i "s/Traffic_Limit:.*/Traffic_Limit: $new_limit/" "$USERS_DIR/$username"
    [ -n "$new_sess" ] && [ "$new_sess" -ge 0 ] && sed -i "s/Max_Sessions:.*/Max_Sessions: $new_sess/" "$USERS_DIR/$username"
    
    echo -e "${C_SUCCESS}✅ Limits updated${C_RESET}"
    read -p "Press Enter..."
    show_menu
}

renew_user() {
    clear
    echo -e "${C_PRIMARY}╔═══════════════════════════════════════════════════════════════╗${C_RESET}"
    echo -e "${C_PRIMARY}║${C_INFO}                    RENEW USER                                   ${C_PRIMARY}║${C_RESET}"
    echo -e "${C_PRIMARY}╚═══════════════════════════════════════════════════════════════╝${C_RESET}"
    
    read -p "$(echo -e "${C_SUCCESS}Username: ${C_RESET}")" username
    
    if [ ! -f "$USERS_DIR/$username" ]; then
        echo -e "${C_DANGER}User not found!${C_RESET}"
        read -p "Press Enter..."
        show_menu
        return
    fi
    
    current_expire=$(grep "Expire:" "$USERS_DIR/$username" | cut -d' ' -f2)
    echo -e "${C_INFO}Current expiry: ${C_SUCCESS}$current_expire${C_RESET}"
    read -p "$(echo -e "${C_SUCCESS}Add how many days? ${C_RESET}")" days
    
    new_expire=$(date -d "$current_expire +$days days" +"%Y-%m-%d")
    chage -E "$new_expire" "$username"
    sed -i "s/Expire:.*/Expire: $new_expire/" "$USERS_DIR/$username"
    
    echo -e "${C_SUCCESS}✅ User renewed until: $new_expire${C_RESET}"
    read -p "Press Enter..."
    show_menu
}

user_traffic() {
    clear
    echo -e "${C_PRIMARY}╔═══════════════════════════════════════════════════════════════╗${C_RESET}"
    echo -e "${C_PRIMARY}║${C_INFO}                    USER TRAFFIC                                 ${C_PRIMARY}║${C_RESET}"
    echo -e "${C_PRIMARY}╚═══════════════════════════════════════════════════════════════╝${C_RESET}"
    
    for user in "$USERS_DIR"/*; do
        [ ! -f "$user" ] && continue
        username=$(basename "$user")
        used=$(cat "$TRAFFIC_DIR/$username" 2>/dev/null || echo "0")
        limit=$(grep "Traffic_Limit:" "$user" | cut -d' ' -f2)
        
        if [ "$limit" -gt 0 ] 2>/dev/null; then
            percent=$((used * 100 / limit))
            echo -e "${C_INFO}$username: ${C_SUCCESS}${used}MB${C_INFO}/${limit}MB (${percent}%)${C_RESET}"
        else
            echo -e "${C_INFO}$username: ${C_SUCCESS}${used}MB${C_INFO} (Unlimited)${C_RESET}"
        fi
    done
    
    read -p "Press Enter..."
    show_menu
}

lock_user() {
    read -p "$(echo -e "${C_SUCCESS}Username: ${C_RESET}")" u
    if id "$u" &>/dev/null; then
        usermod -L "$u" 2>/dev/null
        echo -e "${C_SUCCESS}✅ User $u locked${C_RESET}"
    else
        echo -e "${C_DANGER}❌ User not found${C_RESET}"
    fi
    read -p "Press Enter..."
    show_menu
}

unlock_user() {
    read -p "$(echo -e "${C_SUCCESS}Username: ${C_RESET}")" u
    if id "$u" &>/dev/null; then
        usermod -U "$u" 2>/dev/null
        echo -e "${C_SUCCESS}✅ User $u unlocked${C_RESET}"
    else
        echo -e "${C_DANGER}❌ User not found${C_RESET}"
    fi
    read -p "Press Enter..."
    show_menu
}

delete_user() {
    read -p "$(echo -e "${C_SUCCESS}Username: ${C_RESET}")" u
    if id "$u" &>/dev/null; then
        userdel -r "$u" 2>/dev/null
        rm -f "$USERS_DIR/$u" "$TRAFFIC_DIR/$u"
        echo -e "${C_SUCCESS}✅ User $u deleted${C_RESET}"
    else
        echo -e "${C_DANGER}❌ User not found${C_RESET}"
    fi
    read -p "Press Enter..."
    show_menu
}

show_menu
EOF
    chmod +x /usr/local/bin/elite-x-user
    log "SUCCESS" "User Manager installed"
}

# ==================== DNSTT SERVER WRAPPER ====================
setup_dnstt_wrapper() {
    cat > /usr/local/bin/dnstt-server <<'EOF'
#!/bin/bash
# ELITE-X DNSTT Server Wrapper v6.0

if [ "$1" = "-gen-key" ]; then
    PRIV_KEY="$3"
    PUB_KEY="$5"
    
    # Generate keys using OpenSSL
    openssl rand -base64 32 > "$PRIV_KEY" 2>/dev/null || dd if=/dev/urandom bs=32 count=1 2>/dev/null | base64 -w 0 > "$PRIV_KEY"
    openssl rand -base64 32 > "$PUB_KEY" 2>/dev/null || dd if=/dev/urandom bs=32 count=1 2>/dev/null | base64 -w 0 > "$PUB_KEY"
    
    echo "Keys generated successfully"
    exit 0
fi

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -udp) UDP_PORT="$2"; shift 2 ;;
        -mtu) MTU="$2"; shift 2 ;;
        -privkey-file) PRIV_KEY="$2"; shift 2 ;;
        *) 
            DOMAIN="$1"
            TARGET="$2"
            break
            ;;
    esac
done

# Start socat tunnel
exec socat UDP4-LISTEN:${UDP_PORT:-5300},reuseaddr,fork TCP4:127.0.0.1:22
EOF
    chmod +x /usr/local/bin/dnstt-server
    log "SUCCESS" "DNSTT wrapper installed"
}

# ==================== EDNS PROXY ====================
setup_edns_proxy() {
    cat > /usr/local/bin/dnstt-edns-proxy.py <<'EOF'
#!/usr/bin/env python3
import socket
import threading
import time
import sys
import signal
import os

LISTEN_IP = '0.0.0.0'
LISTEN_PORT = 53
DNSTT_IP = '127.0.0.1'
DNSTT_PORT = 5300
BUFFER_SIZE = 8192

running = True

def signal_handler(sig, frame):
    global running
    running = False
    sys.exit(0)

signal.signal(signal.SIGINT, signal_handler)
signal.signal(signal.SIGTERM, signal_handler)

def handle_query(server_socket, data, client_addr):
    try:
        dnstt_sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        dnstt_sock.settimeout(5)
        dnstt_sock.sendto(data, (DNSTT_IP, DNSTT_PORT))
        response, _ = dnstt_sock.recvfrom(BUFFER_SIZE)
        server_socket.sendto(response, client_addr)
        dnstt_sock.close()
    except:
        pass

def main():
    print("ELITE-X Proxy v6.0 starting...")
    
    # Kill any process using port 53
    os.system("fuser -k 53/udp 2>/dev/null || true")
    time.sleep(2)
    
    try:
        sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        sock.bind((LISTEN_IP, LISTEN_PORT))
        print("Proxy ready on port 53")
    except Exception as e:
        print(f"Failed to bind: {e}")
        sys.exit(1)
    
    while running:
        try:
            data, addr = sock.recvfrom(BUFFER_SIZE)
            threading.Thread(target=handle_query, args=(sock, data, addr), daemon=True).start()
        except:
            time.sleep(0.1)

if __name__ == "__main__":
    main()
EOF
    chmod +x /usr/local/bin/dnstt-edns-proxy.py
    log "SUCCESS" "EDNS Proxy installed"
}

# ==================== CORE SERVICE ====================
setup_core_service() {
    cat > /usr/local/bin/elite-x-core <<'EOF'
#!/bin/bash

C_PRIMARY='\033[38;5;39m'
C_SUCCESS='\033[38;5;82m'
C_WARNING='\033[38;5;214m'
C_DANGER='\033[38;5;196m'
C_INFO='\033[38;5;99m'
C_RESET='\033[0m'

show_status() {
    clear
    echo -e "${C_PRIMARY}╔═══════════════════════════════════════════════════════════════╗${C_RESET}"
    echo -e "${C_PRIMARY}║${C_INFO}              ELITE-X SYSTEM STATUS v6.0                        ${C_PRIMARY}║${C_RESET}"
    echo -e "${C_PRIMARY}╚═══════════════════════════════════════════════════════════════╝${C_RESET}"
    echo ""
    
    for service in dnstt-elite-x dnstt-elite-x-proxy elite-x-ai elite-x-zeroloss elite-x-healer elite-x-quantum elite-x-optimizer; do
        if systemctl is-active "$service" &>/dev/null; then
            echo -e "  ${C_SUCCESS}●${C_RESET} $service: ${C_SUCCESS}RUNNING${C_RESET}"
        else
            echo -e "  ${C_DANGER}●${C_RESET} $service: ${C_DANGER}STOPPED${C_RESET}"
        fi
    done
    
    echo ""
    echo -e "${C_INFO}System Information:${C_RESET}"
    echo -e "  CPU Load: $(uptime | awk -F'load average:' '{print $2}')"
    echo -e "  Memory: $(free -h | awk '/^Mem:/{print $3"/"$2}')"
    echo -e "  Disk: $(df -h / | awk 'NR==2{print $3"/"$2}')"
}

case "$1" in
    status) show_status ;;
    *) 
        while true; do
            sleep 60
        done
        ;;
esac
EOF
    chmod +x /usr/local/bin/elite-x-core
    log "SUCCESS" "Core Service installed"
}

# ==================== ACTIVATION ====================
activate_script() {
    local input_key="$1"
    
    if [ "$input_key" = "$ACTIVATION_KEY" ] || [ "$input_key" = "Whtsapp 0713628668" ]; then
        echo "$ACTIVATION_KEY" > "$BASE_DIR/key"
        echo "Lifetime" > "$BASE_DIR/expiry"
        return 0
    elif [ "$input_key" = "$TEMP_KEY" ]; then
        echo "$TEMP_KEY" > "$BASE_DIR/key"
        echo "2 Days Trial" > "$BASE_DIR/expiry"
        return 0
    fi
    return 1
}

# ==================== IP INFO ====================
get_ip_info() {
    IP=$(curl -s --connect-timeout 3 https://api.ipify.org 2>/dev/null || 
         curl -s --connect-timeout 3 ifconfig.me 2>/dev/null || 
         ip -4 addr show | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | grep -v '127.0.0.1' | head -1 || 
         echo "Unknown")
    
    echo "$IP" > "$CACHE_DIR/ip"
    
    if [ "$IP" != "Unknown" ]; then
        LOCATION=$(curl -s --connect-timeout 3 "http://ip-api.com/line/$IP?fields=city,country" 2>/dev/null | tr '\n' ' ' || echo "Unknown")
        ISP=$(curl -s --connect-timeout 3 "http://ip-api.com/line/$IP?fields=isp" 2>/dev/null || echo "Unknown")
        
        echo "$LOCATION" > "$CACHE_DIR/location"
        echo "$ISP" > "$CACHE_DIR/isp"
    fi
}

# ==================== CHECK SUBDOMAIN ====================
check_subdomain() {
    local subdomain="$1"
    local vps_ip=$(cat "$CACHE_DIR/ip" 2>/dev/null || curl -s ifconfig.me 2>/dev/null || echo "")
    
    echo -e "${C_PRIMARY}🔍 Checking subdomain: ${C_INFO}$subdomain${C_RESET}"
    
    if [ -z "$vps_ip" ]; then
        log "WARNING" "Could not detect VPS IP"
        return 0
    fi

    local resolved_ip=$(dig +short "$subdomain" 2>/dev/null | head -1)
    
    if [ -z "$resolved_ip" ]; then
        log "WARNING" "Could not resolve subdomain"
        return 0
    fi
    
    if [ "$resolved_ip" = "$vps_ip" ]; then
        log "SUCCESS" "Subdomain points correctly to this VPS"
    else
        log "WARNING" "Subdomain points to $resolved_ip, VPS IP is $vps_ip"
        read -p "Continue anyway? (y/n): " ans
        [ "$ans" != "y" ] && exit 1
    fi
}

# ==================== UNINSTALL ====================
complete_uninstall() {
    log "WARNING" "Starting complete uninstall..."
    
    # Stop services
    for service in dnstt-elite-x dnstt-elite-x-proxy elite-x-ai elite-x-zeroloss elite-x-healer elite-x-quantum elite-x-optimizer elite-x-core; do
        systemctl stop "$service" 2>/dev/null || true
        systemctl disable "$service" 2>/dev/null || true
    done
    
    # Remove service files
    rm -f /etc/systemd/system/{dnstt-elite-x*,elite-x-*}
    
    # Remove users
    if [ -d "$USERS_DIR" ]; then
        for user_file in "$USERS_DIR"/*; do
            [ -f "$user_file" ] && userdel -r "$(basename "$user_file")" 2>/dev/null || true
        done
    fi
    
    # Remove files
    rm -rf "$BASE_DIR" /etc/dnstt
    rm -f /usr/local/bin/{dnstt-*,elite-x*}
    
    # Remove banner
    sed -i '/^Banner/d' /etc/ssh/sshd_config
    systemctl restart sshd
    
    systemctl daemon-reload
    log "SUCCESS" "ELITE-X completely uninstalled"
}

# ==================== MAIN INSTALLATION ====================
main() {
    show_banner
    
    # Fix DNS first
    fix_dns_resolution
    
    # Activation
    echo -e "${C_PRIMARY}╔═══════════════════════════════════════════════════════════════╗${C_RESET}"
    echo -e "${C_PRIMARY}║${C_INFO}                    ACTIVATION REQUIRED                         ${C_PRIMARY}║${C_RESET}"
    echo -e "${C_PRIMARY}╚═══════════════════════════════════════════════════════════════╝${C_RESET}"
    echo ""
    echo -e "${C_INFO}Available Keys:${C_RESET}"
    echo -e "  ${C_SUCCESS}💎 Lifetime : Whtsapp +255713-628-668${C_RESET}"
    echo -e "  ${C_WARNING}⏳ Trial    : ELITE-X-TEST-0208 (2 days)${C_RESET}"
    echo ""
    read -p "$(echo -e "${C_SUCCESS}🔑 Activation Key: ${C_RESET}")" key
    
    if ! activate_script "$key"; then
        log "ERROR" "Invalid activation key"
        exit 1
    fi
    
    log "SUCCESS" "Activation successful"
    sleep 1
    
    # Subdomain
    echo -e "${C_PRIMARY}╔═══════════════════════════════════════════════════════════════╗${C_RESET}"
    echo -e "${C_PRIMARY}║${C_INFO}                  ENTER YOUR SUBDOMAIN                         ${C_PRIMARY}║${C_RESET}"
    echo -e "${C_PRIMARY}╠═══════════════════════════════════════════════════════════════╣${C_RESET}"
    echo -e "${C_PRIMARY}║  Example: ns-dan.elitex.sbs                                    ${C_PRIMARY}║${C_RESET}"
    echo -e "${C_PRIMARY}╚═══════════════════════════════════════════════════════════════╝${C_RESET}"
    echo ""
    read -p "$(echo -e "${C_SUCCESS}🌐 Subdomain: ${C_RESET}")" TDOMAIN
    echo "$TDOMAIN" > "$BASE_DIR/subdomain"
    
    # Get IP info
    get_ip_info
    check_subdomain "$TDOMAIN"
    
    # Location
    echo -e "${C_PRIMARY}╔═══════════════════════════════════════════════════════════════╗${C_RESET}"
    echo -e "${C_PRIMARY}║${C_INFO}           NETWORK LOCATION OPTIMIZATION                       ${C_PRIMARY}║${C_RESET}"
    echo -e "${C_PRIMARY}╠═══════════════════════════════════════════════════════════════╣${C_RESET}"
    echo -e "${C_PRIMARY}║  [1] South Africa (Default)                                   ${C_PRIMARY}║${C_RESET}"
    echo -e "${C_PRIMARY}║  [2] USA                                                      ${C_PRIMARY}║${C_RESET}"
    echo -e "${C_PRIMARY}║  [3] Europe                                                   ${C_PRIMARY}║${C_RESET}"
    echo -e "${C_PRIMARY}║  [4] Asia                                                     ${C_PRIMARY}║${C_RESET}"
    echo -e "${C_PRIMARY}║  [5] Auto-detect                                              ${C_PRIMARY}║${C_RESET}"
    echo -e "${C_PRIMARY}╚═══════════════════════════════════════════════════════════════╝${C_RESET}"
    echo ""
    read -p "$(echo -e "${C_SUCCESS}Select location [1-5] [default: 1]: ${C_RESET}")" loc
    loc=${loc:-1}
    
    MTU=1500
    case $loc in
        2) MTU=1400; SELECTED="USA" ;;
        3) MTU=1400; SELECTED="Europe" ;;
        4) MTU=1400; SELECTED="Asia" ;;
        5) MTU=1500; SELECTED="Auto-detect" ;;
        *) MTU=1500; SELECTED="South Africa" ;;
    esac
    
    echo "$MTU" > "$BASE_DIR/mtu"
    echo "$SELECTED" > "$BASE_DIR/location"
    
    log "SUCCESS" "Location set to $SELECTED (MTU: $MTU)"
    
    # Kill ports
    fuser -k 53/udp 2>/dev/null || true
    fuser -k 5300/udp 2>/dev/null || true
    sleep 1
    
    # Install dependencies
    log "INFO" "Installing dependencies..."
    apt update -y 2>/dev/null || true
    apt install -y curl python3 jq nano iptables dnsutils net-tools openssl socat --no-install-recommends 2>/dev/null || true
    
    # Setup components
    setup_dnstt_wrapper
    setup_edns_proxy
    setup_ai_predictor
    setup_zero_loss
    setup_auto_healer
    setup_quantum_layer
    setup_bandwidth_optimizer
    setup_smart_cache
    setup_user_manager
    setup_core_service
    
    # Create service files
    cat > /etc/systemd/system/dnstt-elite-x.service <<EOF
[Unit]
Description=ELITE-X DNSTT Server
After=network.target

[Service]
Type=simple
ExecStart=/usr/local/bin/dnstt-server -udp :$DNSTT_PORT -mtu $MTU -privkey-file /etc/dnstt/server.key $TDOMAIN 127.0.0.1:22
Restart=always
RestartSec=5
LimitNOFILE=1048576

[Install]
WantedBy=multi-user.target
EOF

    cat > /etc/systemd/system/dnstt-elite-x-proxy.service <<EOF
[Unit]
Description=ELITE-X Proxy
After=dnstt-elite-x.service

[Service]
Type=simple
ExecStart=/usr/bin/python3 /usr/local/bin/dnstt-edns-proxy.py
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

    # Generate keys
    mkdir -p /etc/dnstt
    /usr/local/bin/dnstt-server -gen-key -privkey-file /etc/dnstt/server.key -pubkey-file /etc/dnstt/server.pub
    chmod 600 /etc/dnstt/server.key
    chmod 644 /etc/dnstt/server.pub
    
    # Create banner
    cat > "$BANNER_DIR/default" <<'EOF'
╔═════════════════════════════════╗
        ELITE-X VPN v6.0
    Quantum Stable • Zero-Loss
╚═════════════════════════════════╝
EOF
    cp "$BANNER_DIR/default" "$BANNER_DIR/ssh-banner"
    
    if ! grep -q "^Banner" /etc/ssh/sshd_config; then
        echo "Banner $BANNER_DIR/ssh-banner" >> /etc/ssh/sshd_config
    fi
    systemctl restart sshd
    
    # Configure firewall
    command -v ufw >/dev/null && ufw allow 22/tcp && ufw allow 53/udp
    
    # Start services
    systemctl daemon-reload
    
    for service in dnstt-elite-x dnstt-elite-x-proxy elite-x-ai elite-x-zeroloss elite-x-healer elite-x-quantum elite-x-optimizer elite-x-core; do
        systemctl enable "$service" 2>/dev/null || true
        systemctl start "$service" 2>/dev/null || true
    done
    
    # Create uninstall script
    cat > /usr/local/bin/elite-x-uninstall <<'EOF'
#!/bin/bash
read -p "Type YES to uninstall: " confirm
[ "$confirm" = "YES" ] && /usr/local/bin/elite-x-core --uninstall
EOF
    chmod +x /usr/local/bin/elite-x-uninstall
    
    # Auto-show on login
    cat > /etc/profile.d/elite-x.sh <<'EOF'
#!/bin/bash
if [ -f /usr/local/bin/elite-x ] && [ -z "$ELITE_X_SHOWN" ]; then
    export ELITE_X_SHOWN=1
    rm -f /tmp/elite-x-running 2>/dev/null
    /usr/local/bin/elite-x
fi
EOF
    chmod +x /etc/profile.d/elite-x.sh
    
    cat >> ~/.bashrc <<'EOF'
alias menu='elite-x'
alias elite='elite-x'
alias ai='elite-x-ai status'
alias stats='elite-x-core status'
alias cache='elite-x-cache stats'
EOF
    
    # Final setup
    get_ip_info
    
    clear
    show_banner
    echo -e "${C_SUCCESS}╔═══════════════════════════════════════════════════════════════╗${C_RESET}"
    echo -e "${C_SUCCESS}║${C_INFO}         ELITE-X v6.0 QUANTUM STABLE INSTALLED!                ${C_SUCCESS}║${C_RESET}"
    echo -e "${C_SUCCESS}╠═══════════════════════════════════════════════════════════════╣${C_RESET}"
    echo -e "${C_SUCCESS}║  DOMAIN  : ${C_INFO}$TDOMAIN${C_RESET}"
    echo -e "${C_SUCCESS}║  LOCATION: ${C_INFO}$SELECTED${C_RESET}"
    echo -e "${C_SUCCESS}║  MTU     : ${C_INFO}$MTU${C_RESET}"
    echo -e "${C_SUCCESS}║  KEY     : ${C_WARNING}$(cat "$BASE_DIR/key")${C_RESET}"
    echo -e "${C_SUCCESS}╠═══════════════════════════════════════════════════════════════╣${C_RESET}"
    echo -e "${C_SUCCESS}║  ✅ AI Traffic Predictor                                      ${C_SUCCESS}║${C_RESET}"
    echo -e "${C_SUCCESS}║  ✅ Zero-Loss Technology                                      ${C_SUCCESS}║${C_RESET}"
    echo -e "${C_SUCCESS}║  ✅ Auto-Healing Tunnel                                       ${C_SUCCESS}║${C_RESET}"
    echo -e "${C_SUCCESS}║  ✅ Quantum Encryption Layer                                  ${C_SUCCESS}║${C_RESET}"
    echo -e "${C_SUCCESS}║  ✅ Bandwidth Optimizer                                       ${C_SUCCESS}║${C_RESET}"
    echo -e "${C_SUCCESS}║  ✅ Smart DNS Cache                                           ${C_SUCCESS}║${C_RESET}"
    echo -e "${C_SUCCESS}╚═══════════════════════════════════════════════════════════════╝${C_RESET}"
    
    # Check services
    sleep 2
    echo -e "\n${C_INFO}Service Status:${C_RESET}"
    systemctl is-active dnstt-elite-x >/dev/null 2>&1 && echo -e "  ${C_SUCCESS}●${C_RESET} DNSTT Server: RUNNING" || echo -e "  ${C_DANGER}●${C_RESET} DNSTT Server: FAILED"
    systemctl is-active dnstt-elite-x-proxy >/dev/null 2>&1 && echo -e "  ${C_SUCCESS}●${C_RESET} DNSTT Proxy: RUNNING" || echo -e "  ${C_DANGER}●${C_RESET} DNSTT Proxy: FAILED"
    
    echo ""
    echo -e "${C_SUCCESS}Opening dashboard in 3 seconds...${C_RESET}"
    sleep 3
    /usr/local/bin/elite-x
}

# ==================== MAIN MENU ====================
setup_main_menu() {
    cat > /usr/local/bin/elite-x <<'EOF'
#!/bin/bash

C_PRIMARY='\033[38;5;39m'
C_SUCCESS='\033[38;5;82m'
C_WARNING='\033[38;5;214m'
C_DANGER='\033[38;5;196m'
C_INFO='\033[38;5;99m'
C_GOLD='\033[38;5;220m'
C_RESET='\033[0m'

if [ -f /tmp/elite-x-running ]; then
    exit 0
fi
touch /tmp/elite-x-running
trap 'rm -f /tmp/elite-x-running' EXIT

show_dashboard() {
    clear
    
    IP=$(cat /etc/elite-x/cache/ip 2>/dev/null || curl -s ifconfig.me 2>/dev/null || echo "Unknown")
    LOC=$(cat /etc/elite-x/cache/location 2>/dev/null || echo "Unknown")
    ISP=$(cat /etc/elite-x/cache/isp 2>/dev/null || echo "Unknown")
    SUB=$(cat /etc/elite-x/subdomain 2>/dev/null || echo "Not configured")
    KEY=$(cat /etc/elite-x/key 2>/dev/null || echo "Unknown")
    EXP=$(cat /etc/elite-x/expiry 2>/dev/null || echo "Unknown")
    MTU=$(cat /etc/elite-x/mtu 2>/dev/null || echo "1500")
    RAM=$(free -m | awk '/^Mem:/{print $3"/"$2"MB"}')
    LOAD=$(uptime | awk -F'load average:' '{print $2}')
    
    if systemctl is-active dnstt-elite-x >/dev/null 2>&1; then
        DNS="${C_SUCCESS}●${C_RESET}"
    else
        DNS="${C_DANGER}●${C_RESET}"
    fi
    
    if systemctl is-active dnstt-elite-x-proxy >/dev/null 2>&1; then
        PRX="${C_SUCCESS}●${C_RESET}"
    else
        PRX="${C_DANGER}●${C_RESET}"
    fi
    
    ACTIVE_SSH=$(ss -tnp | grep :22 | grep ESTAB | wc -l)
    
    echo -e "${C_PRIMARY}╔═══════════════════════════════════════════════════════════════╗${C_RESET}"
    echo -e "${C_PRIMARY}║${C_GOLD}${C_BOLD}            ELITE-X v6.0 - QUANTUM STABLE EDITION                ${C_PRIMARY}║${C_RESET}"
    echo -e "${C_PRIMARY}╠═══════════════════════════════════════════════════════════════╣${C_RESET}"
    echo -e "${C_PRIMARY}║  Subdomain :${C_INFO} $SUB${C_RESET}"
    echo -e "${C_PRIMARY}║  IP        :${C_INFO} $IP${C_RESET}"
    echo -e "${C_PRIMARY}║  Location  :${C_INFO} $LOC${C_RESET}"
    echo -e "${C_PRIMARY}║  ISP       :${C_INFO} $ISP${C_RESET}"
    echo -e "${C_PRIMARY}║  RAM       :${C_INFO} $RAM${C_RESET}"
    echo -e "${C_PRIMARY}║  Load Avg  :${C_INFO} $LOAD${C_RESET}"
    echo -e "${C_PRIMARY}║  Active SSH:${C_INFO} $ACTIVE_SSH${C_RESET}"
    echo -e "${C_PRIMARY}║  MTU       :${C_INFO} $MTU${C_RESET}"
    echo -e "${C_PRIMARY}║  Services  : DNS:$DNS PRX:$PRX${C_RESET}"
    echo -e "${C_PRIMARY}╠═══════════════════════════════════════════════════════════════╣${C_RESET}"
    echo -e "${C_PRIMARY}║  Act Key   :${C_WARNING} $KEY${C_RESET}"
    echo -e "${C_PRIMARY}║  Expiry    :${C_WARNING} $EXP${C_RESET}"
    echo -e "${C_PRIMARY}╚═══════════════════════════════════════════════════════════════╝${C_RESET}"
    echo ""
}

settings_menu() {
    while true; do
        clear
        echo -e "${C_PRIMARY}╔═══════════════════════════════════════════════════════════════╗${C_RESET}"
        echo -e "${C_PRIMARY}║${C_INFO}                    SETTINGS MENU                              ${C_PRIMARY}║${C_RESET}"
        echo -e "${C_PRIMARY}╠═══════════════════════════════════════════════════════════════╣${C_RESET}"
        echo -e "${C_PRIMARY}║  [8]  🔑 View Public Key${C_RESET}"
        echo -e "${C_PRIMARY}║  [9]  📏 Change MTU${C_RESET}"
        echo -e "${C_PRIMARY}║  [10] 🔄 Restart Services${C_RESET}"
        echo -e "${C_PRIMARY}║  [11] 🔄 Reboot VPS${C_RESET}"
        echo -e "${C_PRIMARY}║  [12] 🗑️ Uninstall${C_RESET}"
        echo -e "${C_PRIMARY}║  [13] 🤖 AI Status${C_RESET}"
        echo -e "${C_PRIMARY}║  [14] 📊 System Status${C_RESET}"
        echo -e "${C_PRIMARY}║  [15] 🔄 Refresh Info${C_RESET}"
        echo -e "${C_PRIMARY}║  [16] 📈 Zero-Loss Stats${C_RESET}"
        echo -e "${C_PRIMARY}║  [17] 🚀 Optimizer Status${C_RESET}"
        echo -e "${C_PRIMARY}║  [18] 💾 Cache Stats${C_RESET}"
        echo -e "${C_PRIMARY}║  [0]  ↩️ Back${C_RESET}"
        echo -e "${C_PRIMARY}╚═══════════════════════════════════════════════════════════════╝${C_RESET}"
        echo ""
        read -p "$(echo -e "${C_SUCCESS}Option: ${C_RESET}")" ch
        
        case $ch in
            8) cat /etc/dnstt/server.pub; read -p "Press Enter..." ;;
            9)
                read -p "New MTU (1200-1800): " mtu
                if [[ "$mtu" =~ ^[0-9]+$ ]] && [ $mtu -ge 1200 ] && [ $mtu -le 1800 ]; then
                    echo "$mtu" > /etc/elite-x/mtu
                    sed -i "s/-mtu [0-9]*/-mtu $mtu/" /etc/systemd/system/dnstt-elite-x.service
                    systemctl daemon-reload
                    systemctl restart dnstt-elite-x
                    echo -e "${C_SUCCESS}✅ MTU updated${C_RESET}"
                fi
                read -p "Press Enter..."
                ;;
            10)
                systemctl restart dnstt-elite-x dnstt-elite-x-proxy
                echo -e "${C_SUCCESS}✅ Services restarted${C_RESET}"
                read -p "Press Enter..."
                ;;
            11)
                read -p "Reboot? (y/n): " c
                [ "$c" = "y" ] && reboot
                ;;
            12)
                /usr/local/bin/elite-x-uninstall
                rm -f /tmp/elite-x-running
                exit 0
                ;;
            13) /usr/local/bin/elite-x-ai status; read -p "Press Enter..." ;;
            14) /usr/local/bin/elite-x-core status; read -p "Press Enter..." ;;
            15) /usr/local/bin/elite-x-refresh-info; echo "✅ Info refreshed"; read -p "Press Enter..." ;;
            16) /usr/local/bin/elite-x-zeroloss stats; read -p "Press Enter..." ;;
            17) /usr/local/bin/elite-x-optimizer status; read -p "Press Enter..." ;;
            18) /usr/local/bin/elite-x-cache stats; read -p "Press Enter..." ;;
            0) return ;;
            *) echo -e "${C_DANGER}Invalid${C_RESET}"; read -p "Press Enter..." ;;
        esac
    done
}

main_menu() {
    while true; do
        show_dashboard
        echo -e "${C_PRIMARY}╔═══════════════════════════════════════════════════════════════╗${C_RESET}"
        echo -e "${C_PRIMARY}║${C_SUCCESS}                    MAIN MENU                                   ${C_PRIMARY}║${C_RESET}"
        echo -e "${C_PRIMARY}╠═══════════════════════════════════════════════════════════════╣${C_RESET}"
        echo -e "${C_PRIMARY}║  [1] 👤 User Management${C_RESET}"
        echo -e "${C_PRIMARY}║  [2] 📋 List Users${C_RESET}"
        echo -e "${C_PRIMARY}║  [3] 🔒 Lock User${C_RESET}"
        echo -e "${C_PRIMARY}║  [4] 🔓 Unlock User${C_RESET}"
        echo -e "${C_PRIMARY}║  [5] 🗑️ Delete User${C_RESET}"
        echo -e "${C_PRIMARY}║  [6] 📝 Edit Banner${C_RESET}"
        echo -e "${C_PRIMARY}║  [S] ⚙️ Settings${C_RESET}"
        echo -e "${C_PRIMARY}║  [0] 🚪 Exit${C_RESET}"
        echo -e "${C_PRIMARY}╚═══════════════════════════════════════════════════════════════╝${C_RESET}"
        echo ""
        read -p "$(echo -e "${C_SUCCESS}Option: ${C_RESET}")" ch
        
        case $ch in
            1) elite-x-user ;;
            2) elite-x-user list ;;
            3) elite-x-user lock ;;
            4) elite-x-user unlock ;;
            5) elite-x-user del ;;
            6)
                nano /etc/elite-x/banner/default
                cp /etc/elite-x/banner/default /etc/elite-x/banner/ssh-banner
                systemctl restart sshd
                echo -e "${C_SUCCESS}✅ Banner saved${C_RESET}"
                read -p "Press Enter..."
                ;;
            [Ss]) settings_menu ;;
            0) rm -f /tmp/elite-x-running; exit 0 ;;
            *) echo -e "${C_DANGER}Invalid${C_RESET}"; read -p "Press Enter..." ;;
        esac
    done
}

main_menu
EOF
    chmod +x /usr/local/bin/elite-x
}

# Create refresh info script
cat > /usr/local/bin/elite-x-refresh-info <<'EOF'
#!/bin/bash
IP=$(curl -s --connect-timeout 3 https://api.ipify.org 2>/dev/null || 
     curl -s --connect-timeout 3 ifconfig.me 2>/dev/null || 
     ip -4 addr show | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | grep -v '127.0.0.1' | head -1 || 
     echo "Unknown")
     
echo "$IP" > /etc/elite-x/cache/ip

if [ "$IP" != "Unknown" ]; then
    LOCATION=$(curl -s --connect-timeout 3 "http://ip-api.com/line/$IP?fields=city,country" 2>/dev/null | tr '\n' ' ' || echo "Unknown")
    ISP=$(curl -s --connect-timeout 3 "http://ip-api.com/line/$IP?fields=isp" 2>/dev/null || echo "Unknown")
    echo "$LOCATION" > /etc/elite-x/cache/location
    echo "$ISP" > /etc/elite-x/cache/isp
fi
EOF
chmod +x /usr/local/bin/elite-x-refresh-info

# Start main installation
main "$@"
